### ISSUE TITLE
Some redundancy with another package (ggthemes)

### ISSUE THREAD

**Issue by RCura** [datarootsio/artyfarty#1]
Hey, your package brings some really cool themes and palette, and you might want to check the [ggthemes](https://github.com/jrnold/ggthemes) package that seems to be very looking alike, for example with your very similar 538 themes :)

A merge of your themes/palettes might be a cool thing fir the useRs :)

**Comment by bart6114** [comment]
fair point, I'll check with @jrnold

**Comment by bart6114** [comment]
still a fair point, but will not merge for now

**Comment by jrnold** [comment]
It was cool to see your package. And losing the package name artyfarty would be a net loss for the world. It may still be worth merging the 538 themes.
